server:
  port: 8761

spring:
  application:
    name: bft-discovery-service

eureka:
  client:
    register-with-eureka: false # register eureka server
    fetch-registry: false # connect eureka server
